appConfig:
  app:
    title: "Backstage on Minikube"
  integrations:
    github:
      - host: github.com
  kubernetes:
    serviceLocatorMethod: http
    inCluster: true

serviceAccount:
  create: true
  name: backstage