appConfig:
  app:
    title: "Backstage on Minikube"
    baseUrl: http://localhost:7007
  backend:
    baseUrl: http://localhost:7007
    cors:
      origin: http://localhost:3000
      methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
      credentials: true
  auth:
    environment: development
    providers:
      guest:
        dangerouslyAllowOutsideDevelopment: true
  integrations:
    github:
      - host: github.com
  kubernetes:
    serviceLocatorMethod: multiTenant
    clusterLocatorMethods:
      - type: config
        clusters:
          - url: https://kubernetes.default.svc
            name: local-cluster
            authProvider: serviceAccount
            skipTLSVerify: true
            skipMetricsLookup: false

serviceAccount:
  create: true
  name: backstage
  annotations: {}
  automountServiceAccountToken: true

backstage:
  extraEnvVars:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace