apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-applicationset
  namespace: argocd
  labels:
    app.kubernetes.io/name: apps-applicationset
    app.kubernetes.io/component: application-set
spec:
  generators:
  - git:
      repoURL: https://github.com/arnfox/argo.git
      revision: main
      directories:
      - path: k8s/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{path.basename}}'
        app.kubernetes.io/component: application
        managed-by: applicationset
    spec:
      project: default
      source:
        repoURL: https://github.com/arnfox/argo.git
        path: "{{path}}"
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
