apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd           # Argo CD's own namespace
spec:
  project: default
  source:
    repoURL: https://github.com/arnfox/argo.git
    path: services/backstage           # folder below
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true