apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello.fullname" . }}-config
  labels:
    {{- include "hello.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>{{ .Values.message.title }}</title></head>
      <body>
        <h1>{{ .Values.message.title }}</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
      volumes:
      - name: html
        configMap:
          name: {{ include "hello.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
